using System.Diagnostics;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Mono.TextTemplating;

//using Mono.TextTemplating;

namespace SignalF.Configuration.SourceGenerator;

public abstract class GeneratorBase : IncrementalGenerator
{

    protected override void OnInitialize()
    {
        //Debugger.Launch();
        var attributes = GetAttributes();
        foreach (var attribute in attributes)
        {
            RegisterSourceOutputForAttribute(attribute);
        }
    }

    private void RegisterSourceOutputForAttribute(string attributeTypeName)
    {
        //Debugger.Launch();
        var pipeline = Context.SyntaxProvider.ForAttributeWithMetadataName(
            attributeTypeName,
            static (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax,
            static (context, _) => context);

        Context.RegisterSourceOutput(pipeline, Execute);
    }

    private void Execute(SourceProductionContext sourceContext, GeneratorAttributeSyntaxContext syntaxContext)
    {
        TemplateGenerator _generator = new();

        //Debugger.Launch();
        var symbol = syntaxContext.TargetSymbol;
        var className = syntaxContext.TargetSymbol.Name;
        var classNamespace = symbol.ContainingNamespace.ToDisplayString();
        var globalNamespace = syntaxContext.SemanticModel.Compilation.Assembly.Name;

        _generator.AddParameter("", "", "className", className);
        _generator.AddParameter("", "", "classNamespace", classNamespace);
        _generator.AddParameter("", "", "globalNamespace", globalNamespace);
        
        foreach (var templateName in GetTemplateNames())
        {
            var template = LoadTemplate(templateName);
            if (!string.IsNullOrEmpty(template))
            {
                //var content = string.Format(template, @namespace, className, globalNamespace);

                var parsed = _generator.ParseTemplate(templateName, template);
                var settings = TemplatingEngine.GetSettings(_generator, parsed);
                settings.CompilerOptions = "-nullable:enable";

                var compiled = _generator.CompileTemplateAsync(template).GetAwaiter().GetResult();
                var content = compiled.Process();
                //var (outputName, content, success) = _generator.ProcessTemplateAsync(templateName, template, $"{className}{templateName}")
                //    .ConfigureAwait(true).GetAwaiter().GetResult();


                var x = $$"""﻿
// <auto-generated />
#pragma warning disable

using Microsoft.Extensions.DependencyInjection;
using SignalF.Configuration;
using SignalF.Configuration.Devices;
using SignalF.Controller.Configuration;
using SignalF.Datamodel.Hardware;

namespace SourceGenerator.dev;

public partial interface
    IClass2SConfigurationBuilder : IClass2SConfigurationBuilder<IClass2SConfigurationBuilder,
        IDeviceConfiguration, Class2SDeviceOptions>
{
}

public partial interface
    IClass2SConfigurationBuilder<out TBuilder, in TConfiguration, in TOptions> : IDeviceConfigurationBuilder<TBuilder, TConfiguration,
        TOptions>
    where TBuilder : IDeviceConfigurationBuilder<TBuilder, TConfiguration, TOptions>
    where TConfiguration : IDeviceConfiguration
    where TOptions : Class2SDeviceOptions
{
}

public partial class Class2SConfigurationBuilder
    : Class2SConfigurationBuilder<Class2SConfigurationBuilder, IClass2SConfigurationBuilder,
          IDeviceConfiguration, Class2SDeviceOptions>, IClass2SConfigurationBuilder
{
    protected override IClass2SConfigurationBuilder This => this;
}

public abstract partial class Class2SConfigurationBuilder<TImpl, TBuilder, TConfiguration, TOptions>
    : DeviceConfigurationBuilder<TImpl, TBuilder, TConfiguration, TOptions>
      , IClass2SConfigurationBuilder<TBuilder, TConfiguration, TOptions>
    where TBuilder : IClass2SConfigurationBuilder<TBuilder, TConfiguration, TOptions>
    where TImpl : Class2SConfigurationBuilder<TImpl, TBuilder, TConfiguration, TOptions>
    where TConfiguration : IDeviceConfiguration
    where TOptions : Class2SDeviceOptions
{
}

""";
                 
                //if (success)
                {
                    sourceContext.AddSource($"{className}{templateName}.g.cs", x);
                }
                
                // sourceContext.AddSource($"{className}{templateName}.g.cs", content);
            }
        }
    }

    protected abstract string[] GetTemplateNames();

    protected abstract string[] GetAttributes();
}
